### ISSUE TITLE
Sign a Yii2 generated E-Mail with DKIM

### ISSUE THREAD

**Issue by kasoft** [yiisoft/yii2-swiftmailer#108]
I'm trying to sign a E-Mail with DKIM but it's not working with yii2-swiftmailer als Classes seems not to be working together. Maybe there is just some work needed to fix this? Here is my Approach:

1. Generate E-Mail 
```
        $message = Yii::$app->mailer->compose();
        $message->setTextBody($msg);
        $message->setSubject($sub);
```

But how to sign with DKIM? It would be perfect to just add 
```
$signer = new DkimSigner($private_key, 'test.com', 'test'); 
$message->signDKIM($signer)->send();
```

Also what is not working
`$signedEmail = $signer->sign($emailObject);`
But $emailObject has to be a Symfony Mail Object and is not working with yii2-symfony Object

Workaround?
So i create a new Symfony\Mail Object, set all Data like $to, $from, $text, ... and sign it. But that i need to transfer the DKIM-Signature to the yii2-symfony Mailheader. But there is nothing to get the current Header.

So I'm stuck here ...

**Comment by mtangoo** [comment]
No support is available, nor is planned. PR will be appreciated

**Comment by kasoft** [comment]
OK, thanks for the update so there is no missing clue, this needs to be adopted. i solved this by letting my e-mail provider taking care of this. so maybe this is also not needed - otherwise i can try to prepare a suggestion.

**Comment by mtangoo** [comment]
I never needed in all my years of using email.
I will close this, feel free to make PR when you can
