### ISSUE TITLE
Exception 'Swift_TransportException' with message 'Expected response code 250 but got code "502"

### ISSUE THREAD

**Issue by wmgm183** [yiisoft/yii2-swiftmailer#109]
/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:383

Stack trace:
#0 /www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(281): Swift_Transport_AbstractSmtpTransport->_assertResponseCode('502 Timeout fro...', Array)

'version' => '2.0.7.0'

**Comment by samdark** [comment]
502 means a problem at SMTP side, not the Yii code.

**Comment by wmgm183** [comment]
502 question can not add a wrong mechanism to judge it? Although the problem is with the SMTP server. Can you add a mechanism to your code. Throws an exception. Or throw an exception after 3 retries
