### ISSUE TITLE
Can not catch Swiftmailer's exceptions

### ISSUE THREAD

**Issue by qpi** [yiisoft/yii2-swiftmailer#11]
In my project if the email sending is failed, I have to rollback all my previous tasks (because it is a user registration, I have to delete the created user). I see the Swift_TransportException in the log, but I can not catch it in my try block. Also strange that the request replies HTTP Redirection 302 error code and redirects me to the same controller's view action with an id (which is the id of the previously created user in my action)

My configuration is:
```
'mailer' => [
	'class' => 'yii\swiftmailer\Mailer',
	'useFileTransport' => false,
	'transport' => [
		'class' => 'Swift_SmtpTransport',
		'host' => 'email-smtp.us-west-2.amazonaws.com',
		'username' => '*******',
		'password' => '*******',
		'port' => 587,
		'encryption' => 'tls'
	],
],
```
the code is:
```
try {
	...
	Yii::$app->mailer->compose()
	->setFrom('from@email.com')
	->setTo($model->email)
	->setSubject('Activation email')
	->setTextBody('Activation url: ' . $activationUrl)
	->setHtmlBody('Activation url: ' . $activationUrl)
	->send();
	...
} catch (Exception $e) {
	//delete user here
}
```

**Comment by klimov-paul** [comment]
This does not sound like Yii isssue: If you have any problem with `try...catch` block you should report it to php.net.
Still you may try to enforce catching all exceptions, which perhaps you missed specifying `\Exception`:
```php
try {
    ...
} catch (\Exception $e) {
    //delete user here
}
```

**Comment by qpi** [comment]
Why have U closed the issue immediately??? Maybe You misunderstood me, it is not a php level problem, I can catch any kind of Exceptions, except the Exceptions from Swiftmailer. So for me it seems yii2-swiftmailer or swiftmailer level issue. Please reopen the my issue!

**Comment by qpi** [comment]
You're right finally the problem was the missing \
I tought that I haven't declared the:
use yii\base\Exception;
but it was there and that's why just the could catch the Yii's Base Exceptions.
Sorry and thank's
