### ISSUE TITLE
Setting Dynamic content for queued messages

### ISSUE THREAD

**Issue by alladas** [yiisoft/yii2-swiftmailer#12]
Hello All,
In a multilanguage site context, messages are sent in real time translated into the language in use by the user.
I am trying to send site messages from a queue using a cron job.
The case is that the messages are added to queue only in the sourceLanguage.
What I would like is to populate the queue with already translated messages - in the user language according to the locale set in their profile. So users will get messages in their language.
I can't find a way to do that.
Any tips or hints?

**Comment by klimov-paul** [comment]
@alladas, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
