### ISSUE TITLE
Call to undefined method Swift_RfcComplianceException::getName().

### ISSUE THREAD

**Issue by rohitmel** [yiisoft/yii2-swiftmailer#13]
exception 'Swift_RfcComplianceException' with message 'Address in mailbox given [xxx’xxx@xxx.com.au] does not comply with RFC 2822, 3.6.2.' in xxxxxxxxxxxxx\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mime\Headers\MailboxHeader.php:348

**Comment by klimov-paul** [comment]
@rohitmel, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.
