### ISSUE TITLE
Not valid html tag

### ISSUE THREAD

**Issue by adiramardiani** [yiisoft/yii2-swiftmailer#16]
I try yii2 advanced template, but for email (example reset password) give not valid html tag like `=3D"` etc, please check

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.=
org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns=3D"http://www.w3.org=
/1999/xhtml">
<head>
    <meta http-equiv=3D"Content-Type" con=
tent=3D"text/html; charset=3DUTF-8" />
    <title></title>
    <=
/head>
<body>
        <div class=3D"password-reset">
    <=
p>Hello user,</p>

    <p>Follow the link below to r=
eset your password:</p>

    <p><a href=3D"http://domain.com/admin/=
reset-password?token=3DRkyjyDtRrLqcwnmgYYFwqEL5389vI2yB_1440474633">http:/=
/domain.com/admin/reset-password?token=3DRkyjyDtRrLqcwnmgYYFwqEL5389vI2yB_144=
0474633</a></p>
</div>
    </body>
</html>
```

**Comment by samdark** [comment]
That's normal encoding for emails.

**Comment by adiramardiani** [comment]
But why when I insert `inline css` or `link css`, the css rules are not working. 
And when I saw the original `source` other email is not like that, like normal html ?

**Comment by samdark** [comment]
How do you form this email?

**Comment by adiramardiani** [comment]
I use my google account (with smtp google), try sending to google and yahoo mail, give the same result like my code above. For previous version I think the css rules is applied, but now (I don't know, since swiftmailer, yii2 swiftmailer, or yii base mail update) the css rules are not working. I try to fresh install yii2 advanced template and test email with reset password form, is not apply the css rules.

**Comment by klimov-paul** [comment]
Unable to reproduce: HTML content is sent fine.
Perhaps there is something wrong in your environment - try to send email from another server via another SMTP.
Also try t osend HTML email via other means (not Yii) through your current SMTP.

**Comment by matih** [comment]
Hi, I think that it's a real bug, 
I also get this problem that the encoding of the message adds `3D` and broke's the HTML, 
In my example the `token` I sent was became invalid.
I use `'useFileTransport' => true,` 
So, the problem is the encoding level. and not in the server or etc.

Screenshot attached.

![yii-swiftmailer-bug](https://cloud.githubusercontent.com/assets/1487861/16948313/ae140c26-4dbc-11e6-81e0-6d0a0a39a17b.png)

**Comment by cebe** [comment]
that is valid email encoding of the content, if you open it in an email program it should display fine.

`=3D` is the encoding of a `=` according to `Content-Transfer-Encoding` header you see above in line 24.
