### ISSUE TITLE
Send mails on PHP 5.6 without correct OpenSSL certificate

### ISSUE THREAD

**Issue by TomaszKane** [yiisoft/yii2-swiftmailer#17]
Hi,
PHP 5.6 sets SSL flag `verify_peer` to `true`, so without proper SSL config sending e-mails cause error:
> PHP Warning – yii\base\ErrorException
> stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

It'll be great to set this flag in Yii2 main config file -> components -> mailer

**Comment by gharach** [comment]
i have the same problem , how can u fixed that without set it in config file?

**Comment by TomaszKane** [comment]
Hotfix: http://stackoverflow.com/questions/26971712/swiftmailer-connection-established-error/29448735#29448735

**Comment by gharach** [comment]
it seams have to hack the code , by the way thank u for replying ,this is work and do my job ;)

**Comment by TomaszKane** [comment]
Yes, this is a hotfix, not solution :-)

**Comment by samdark** [comment]
I don't think we can fix it from within Yii.

**Comment by cocuba** [comment]
for those who wants to allow self signed certificate, the solution i've found its modifying `/vendor/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php` in the line 263:

`$this->_stream = @stream_socket_client($host.':'.$this->_params['port'], $errno, $errstr, $timeout, STREAM_CLIENT_CONNECT, stream_context_create(array('ssl'=>['verify_peer'=>false, 'verify_peer_name'=>false, 'allow_self_signed'=>true])));`

**Comment by infocomsrl** [comment]
Te options can be setted this way:

`			
'transport' => [
				'class' => 'Swift_SmtpTransport',
				'host' => $smtphost,
				'username' => $smtpuser,
				'password' => $smtppass,
				'port' => $smtpport,
				'encryption' => $smtpsecure,
				'streamOptions' => [
					'ssl' => [
						'allow_self_signed' => true,
						'verify_peer' => false,
						'verify_peer_name' => false,
					],
				],
			],
`

**Comment by phuong17889** [comment]
@infocomsrl worked for me. Thanks

**Comment by corics15** [comment]
@infocomsrl , thanks for posting and sharing your solution. Worked for me!

**Comment by mahpudin** [comment]
@infocomsrl worked for me. Thanks

**Comment by Chienle** [comment]
@infocomsrl thanks a lot!

**Comment by NENJAK** [comment]
Hi,
Infocom, sorry, where exactly (which php class?) you call the transport options?

**Comment by TomaszKane** [comment]
You don't call transport options, just put it into app config:

```
'components' => [
    'mailer' => [
        'class' => 'yii\swiftmailer\Mailer',
        'transport' => [
        // ...
        ],
    ],
]
```

**Comment by Xuzan9396** [comment]
```
Whoops, looks like something went wrong.

1/1
ErrorException in StreamBuffer.php line 94:
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

**Comment by Xuzan9396** [comment]
@infocomsrl 
**why?**

**Comment by naimmalek** [comment]
@cocuba its working in yii2 Thanks a lot !!!!

**Comment by bigguy** [comment]
streamOptions' => [
                    'ssl' => [
                        'allow_self_signed' => true,
                        'verify_peer' => false,
                        'verify_peer_name' => false,
                    ],
                ],

Work for me..

**Comment by germanoricardi** [comment]
@infocomsrl its working, thanks!

**Comment by TheVBProgrammer** [comment]
You can put the option into config, it is under streamOptions array: 
```
'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'viewPath' => '@common/mail',
            'useFileTransport' => false,//set this property to false to send mails to real email addresses
            //comment the following array to send mail using php's mail function
            'transport' => [
                'class' => 'Swift_SmtpTransport',
                'host' => 'smtp.gmail.com',
                'username' => 'my@gmail.com',
                'password' => 'mypassword',
                'port' => '587',
                'encryption' => 'tls',
                'streamOptions'=>[
                   'ssl'=>[
                        'verify_peer'=>false,
                        'verify_peer_name'=>false,
                        'allow_self_signed'=>true
                  ]
                ]
            ],
        ],
```

**Comment by srkkhan** [comment]
@cocuba  its working in yii2 Thanks a lot !!!!

**Comment by alastrols** [comment]
Work Thanks.
