### ISSUE TITLE
get message body

### ISSUE THREAD

**Issue by cbhp** [yiisoft/yii2-swiftmailer#18]
After composing a message it would be nice to get its bodies:
```php
$message = Yii::$app->mailer->compose([
	'html' => 'welcome-html',
	'text' => 'welcome-text',
]);

$subject = $message->getSubject(); // works
$html = $message->getHtmlBody();   // missing
$plain = $message->getTextBody();  // missing

// e.g., storing html and plain in a database for later usage, preview, ... here
```

**Comment by klimov-paul** [comment]
See https://github.com/yiisoft/yii2/issues/12469#issuecomment-245220190

**Comment by hserge** [comment]
Try:
$message->getSwiftMessage()->getBody()

**Comment by tomaszkane** [comment]
I can provide code to handle `getTextBody()` and `getHtmlBody()`.

**Comment by machour** [comment]
@tomaszkane please open a new issue, new comments on closed issues will most likely be ignored.
