### ISSUE TITLE
Does yii2-swiftmailer support sending base64 emails

### ISSUE THREAD

**Issue by tuanvu-se** [yiisoft/yii2-swiftmailer#20]
Dear,
I'm trying to use base64 image in Html body email and send it to gmail. But the email is not display image because all of resource of image is removed in email. So I would like to ask that

How could I use yii2-swiftmailer to send an email with base64 image (embed in-line image) correctly ?

Thank you!

**Comment by cebe** [comment]
are you sure it is a problem with the library and that google does not strip out something from the mail? Try to view it in a different email program like for example Mozilla Thunderbird.

**Comment by cebe** [comment]
you may also paste the source of the email so we can check if it is genereated correctly.

**Comment by tuanvu-se** [comment]
Thanks for your support. After I checked again, I realized that it was still display on Thunderbird. I guess that Gmail has filter base 64 image. May be I have to use method image attachment to display it in Gmail. 

My source code is quite simple, it just like that 
 Yii::$app->mailer->compose()
            ->setTo($email)
            ->setFrom([$this->email => $this->name])
            ->setSubject("Contact Form")
            ->setCharset('utf-8')
            ->setHtmlBody($emailContent)
            ->send();

**Comment by cebe** [comment]
> May be I have to use method image attachment to display it in Gmail.

yes I think so. Closing as it is not an issue with this package.
