### ISSUE TITLE
Missing setReturnPath

### ISSUE THREAD

**Issue by ber5ien** [yiisoft/yii2-swiftmailer#23]
Hi,

I have noticed that the following is missing from this plugin setReturnPath

http://swiftmailer.org/docs/messages.html#setting-the-return-path-bounce-address

Setting the Return-Path: (Bounce) Address¶

The Return-Path: address specifies where bounce notifications should be sent and is set with the setReturnPath() method of the message.

You can only have one Return-Path: and it must not include a personal name.

To set the Return-Path: address:

Call the setReturnPath() method on the Message.
Bounce notifications will be sent to this address.

1
$message->setReturnPath('bounces@address.tld');

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/issues/10275

**Comment by klimov-paul** [comment]
Resolved by commit b0f7f9fa13554384ee9bc6135ac7f31a5f503b27
