### ISSUE TITLE
Don't validate email from 2 level domain

### ISSUE THREAD

**Issue by rumatakira** [yiisoft/yii2-swiftmailer#28]
return [
    'adminEmail' => 'admin@mafiaonlinerolegame.a2hosted.com',

cause:

Address in mailbox given [] does not comply with RFC 2822, 3.6.2.
1. in /home/kira/lampstack-7.0.4-0/apache2/mafia-yii/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php at line 348

**Comment by klimov-paul** [comment]
This should be reported to swiftmailer project.
