### ISSUE TITLE
Send email by console

### ISSUE THREAD

**Issue by ipppinto** [yiisoft/yii2-swiftmailer#30]
I want send email by console with Swift_SmtpTransport and I think that is a issue.

The same transport settings work in common/config/main-local.php and don't work in console/config/main-local.php.

In console/config/main-local.php I have (is a copy of 
common/config/main-local.php):
```
<?php
return [
    'components' => [        
        'mail' => [
            'class' => 'yii\swiftmailer\Mailer',
            'viewPath' => '@common/mail',
            'htmlLayout' => '@common/mail/layouts/html',
            'textLayout' => '@common/mail/layouts/text',  // custome layout        
            'transport' => [
                'class' => 'Swift_SmtpTransport',
                'host' => 'gator.hostgator.com',
                'username' => 'test@pix.com',
                'password' => '*******',
                'port' => '465',
                'encryption' => 'ssl',
            ],
        ],
    ],    
];
```
With this configuration (and in common the settings are the same and work) I load the script by command and no email send and no error.

With below (I delete the transport settings) I run the same script by command and the email send ok:
```
<?php
return [
    'components' => [        
        'mail' => [
            'class' => 'yii\swiftmailer\Mailer',
            'viewPath' => '@common/mail',
            'htmlLayout' => '@common/mail/layouts/html',
            'textLayout' => '@common/mail/layouts/text',  // custome layout        
        ],
    ],    
];
```
In console/controllers/CronController I have this:
```
<?php

namespace console\controllers;

use yii\console\Controller;
use backend\models\Definicoes;
use common\models\Acordo;
use Yii;

/**
 * Cron controller
 */
class CronController extends Controller {

    public function actionIndex() {
        $data_hoje = date('Y-m-d');
        $model_definicoes = Definicoes::find()->one();

        Yii::$app->mail->compose('@common/mail/cron_acordo', ['model_definicoes' => $model_definicoes])
           ->setFrom([Yii::$app->params['adminEmail'] => Yii::$app->params['nome']])
           ->setSubject('Alert')
           ->setTo('ideinto@gmail.com')     
           ->send();        
    }
}
```

Why this happen? I can´t use transport in console? 
I verify in Cpanel the host, user and pass and is ok. This settings work fine in common where I send email without problems.
In the log I don't have any error.
How can I verify where is the problem?

Thanks!

| Yii vesion: 2.0.7       |
| PHP version: 5.4      |
| Operating system: Linux |

**Comment by cebe** [comment]
I have already told you: https://github.com/yiisoft/yii2/issues/11409#issuecomment-213730691

Please note, that the GitHub Issue Tracker is for bug reports and feature requests only.

We are happy to help you on the [support forum](http://www.yiiframework.com/forum/), on [IRC](http://www.yiiframework.com/chat/) (#yii on freenode), or [Gitter](https://gitter.im/yiisoft/yii2).

Please use one of the above mentioned resources to discuss the problem.
