### ISSUE TITLE
SwiftMailer 6.0+ support

### ISSUE THREAD

**Issue by francislavoie** [yiisoft/yii2-swiftmailer#31]
A breaking change in 6.0+ is that they removed the `newInstance()` static methods in all of the classes. This library uses that function in `Mailer.php` function `createSwiftMailer()`. Changing it to `return new \Swift_Mailer($this->getTransport());` shouldn't break old versions of SwiftMailer, and would allow support for 6.0+

Some context: I need SwiftMailer dev 6.0+ in my project because it implements stream context options, see here: https://github.com/swiftmailer/swiftmailer/commit/d791ebe2266d5f997a6f712fa8892620395b0c0e

I'm not sure if this is the only change needed, I haven't tried it yet. There may be other breaking changes in 6.0 that I haven't noticed, see here: https://github.com/swiftmailer/swiftmailer/blob/master/CHANGES

Thanks

**Comment by francislavoie** [comment]
The stream context options were included in their 5.4.2 release so this is no longer an issue for me, but the issue is still valid, the 6.0 release, whenever it comes, will break this extension's use of `newInstance()`

5.4.2 changelog here: https://github.com/swiftmailer/swiftmailer/blob/5.x/CHANGES

**Comment by cebe** [comment]
The `Swift_MailTransport` class is deprecated since version 5.4.5, which has been released today:

- https://github.com/swiftmailer/swiftmailer/blob/e34123081ded3fbb4d8ccdff9ece3a4c8f6046b5/CHANGES#L10-L18
- http://www.yiiframework.com/news/122/recent-security-issues-with-phpmailer-and-swiftmailer/

This is currently the default transport class.

**Comment by klimov-paul** [comment]
I am closing this issue, since there is no 6.0 release yet and noot even a planned date.
The topic should be reconsidered **after** Swiftmailer major release.

**Comment by cebe** [comment]
Swiftmailer 6.0 is a thing now: https://github.com/swiftmailer/swiftmailer/releases/v6.0.0

here is the changelog: https://github.com/swiftmailer/swiftmailer/blob/v6.0.0/CHANGES#L4

**Comment by klimov-paul** [comment]
https://github.com/swiftmailer/swiftmailer/blob/v6.0.0/CHANGES#L17

Minimal PHP version is 7.0 for it now.

**Comment by klimov-paul** [comment]
Resolved by commit 3878a9b
