### ISSUE TITLE
Calling unknown method: yii\swiftmailer\Message::setReturnPath()

### ISSUE THREAD

**Issue by rumatakira** [yiisoft/yii2-swiftmailer#39]
![1](https://cloud.githubusercontent.com/assets/16696651/20694895/9ffd92a8-b5e8-11e6-81c9-378773da59df.png)
![2](https://cloud.githubusercontent.com/assets/16696651/20694897/a0057c8e-b5e8-11e6-8e2e-7e1f9c590376.png)
![4](https://cloud.githubusercontent.com/assets/16696651/20694896/a00123d2-b5e8-11e6-96fd-5964be2b5731.png)

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-swiftmailer/blob/master/tests/MessageTest.php#L199
https://github.com/yiisoft/yii2-swiftmailer/blob/master/tests/MessageTest.php#L211
