### ISSUE TITLE
Swift_TransportException

### ISSUE THREAD

**Issue by pptyasar** [yiisoft/yii2-swiftmailer#41]
Mail was working perfect 
but today I got this error in all project 

> Expected response code 250 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at
> 535 5.7.8 https://support.google.com/mail/?p=BadCredentials 189sm6173361pgh.5 - gsmtp

**Comment by pptyasar** [comment]
I think there is some issue @klimov-paul

**Comment by cebe** [comment]
@pptyasar what did you change to get this error?

**Comment by samdark** [comment]
@pptyasar have you updated any code via composer before getting it?

**Comment by pptyasar** [comment]
No @samdark

**Comment by cebe** [comment]
then it is unlikely a yii code issue.

**Comment by pptyasar** [comment]
The code was working perfectly in all my projects but today onwards its showing this error

**Comment by pptyasar** [comment]
In config 


'mailer' => [
             'class' => 'yii\swiftmailer\Mailer',
             'useFileTransport' => false,
             'transport' => [
                 'class' => 'Swift_SmtpTransport',
                 'host' => 'smtp.gmail.com',
                 'username' => 'myEmail',
                 'password' => 'myPass',
                 'port' => '587',
                 'encryption' => 'tls',
             ],
        ],


In Action 

             Yii::$app->mailer->compose()
             ->setFrom(Yii::$app->params['adminEmail'])
             ->setTo($model->email)
             ->setSubject(" Subjetc")
              ->setHtmlBody($message)
             ->send();

**Comment by samdark** [comment]
Then it's definitely not the issue we can solve since it's not within Yii core or this extension code.

Since this is issue tracker which is for bugs and feature requests only, please use forums, IRC etc. listed in the message above. Thanks.
