### ISSUE TITLE
Swift_Mime_HeaderFactory not found in Swift_Mime_SimpleHeaderFactory

### ISSUE THREAD

**Issue by djnordeen** [yiisoft/yii2-swiftmailer#44]
### What steps will reproduce the problem?
Not sure why the email is not sent.  Not sure how to debug this.  I checked all config files, advanced template, only one mailer component.
### What's expected?
autoresponse email sent. 
### What do you get instead?
Error:  [error][yii\base\ErrorException:1] exception 'yii\base\ErrorException' with message 'Interface 'Swift_Mime_HeaderFactory' not found' in /home/lansingc/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderFactory.php:17

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |2.0.8
| PHP version      |5.6.3
| Operating system | web host apache

**Comment by klimov-paul** [comment]
Are you able to send email using plain `swiftmailer` without Yii being involved?

**Comment by djnordeen** [comment]
Paul, Yes I can send mail through php.

**Comment by djnordeen** [comment]
Paul,
I had updated the site.  Swift mailer was updated to 5.4.5 dev.

I reloaded an older version of Swiftmailer 5.4.3.
It works.  Thanks

**Comment by klimov-paul** [comment]
Then it is not Yii issue. You should report it to swiftmailer project.
