### ISSUE TITLE
Why remove method getLogger()?

### ISSUE THREAD

**Issue by goffyara** [yiisoft/yii2-swiftmailer#48]
Why remove method getLogger()?

How I can get log of last sending message to save in file, db, etc?

https://github.com/yiisoft/yii2/issues/7524#issuecomment-77061109
https://github.com/yiisoft/yii2-swiftmailer/issues/4

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2

**Comment by klimov-paul** [comment]
> Why remove method getLogger()?

Method `getLogger()` have never existed at `yii2-swiftmailer`, so I can provide you any answer.
