### ISSUE TITLE
Got Expected response code 354 but got code "503", with message "503 Bad sequence of commands [@sm190202] " when sending emails in a loop

### ISSUE THREAD

**Issue by Andrew-Wang** [yiisoft/yii2-swiftmailer#52]
When I send emails in a loop, I got the exception: Expected response code 354 but got code "503", with message "503 Bad sequence of commands [@sm190202]", I found there's a fix fixed this error in [mustafaileri/swiftmailer commit d289295](https://github.com/mustafaileri/swiftmailer/commit/d289295235488cdc79473260e04e3dabd2dac3ef) , could you please merge the changes in the commit?

**Comment by klimov-paul** [comment]
This issue does not belong to the Yii.
If you are concerned about it, you should report it to [SwiftMailer project](https://github.com/swiftmailer/swiftmailer)
