### ISSUE TITLE
Priority setup as High if value is empty

### ISSUE THREAD

**Issue by ber5ien** [yiisoft/yii2-swiftmailer#54]
### What steps will reproduce the problem?
set a priority with empty value $priority = ''
### What's expected?
priority "Normal" or not setup
### What do you get instead?
Priority is setup as High

### Additional info
Fixed in my code by not setting up priority if value is empty

if (isset($posted['Tickets']['priority']) AND !empty($posted['Tickets']['priority'])){
            if(method_exists($message,'setPriority')) {
              $message->setPriority($posted['Tickets']['priority']);
            }            
      }

| Q                       | A
| ----------------------- | ---
| Yii version             |
| Yii SwiftMailer version |             "version": "2.0.7",
| SwiftMailer version     |             "version": "v5.4.8",
| PHP version             |
| Operating system        | Linux

**Comment by klimov-paul** [comment]
Rejected: such change creates an inconsistent code.
