### ISSUE TITLE
swiftmailer breaks support for php5

### ISSUE THREAD

**Issue by tsdogs** [yiisoft/yii2-swiftmailer#55]
This is not a direct problem, though swiftmailer broke php 5 support in 6.0.2 by using the $x = $y ?? 0; syntax
forcing the project to use version 6.0.1 fixes the problem.

**Comment by schmunk42** [comment]
- `yii2-swiftmailer 2.0.x` uses `swiftmailer 5.x`
- `yii2-swiftmailer 2.1.x` uses `swiftmailer 6.x`

Swiftmailer 6.0.0 already has the [correct PHP constraint](https://github.com/swiftmailer/swiftmailer/blob/v6.0.0/composer.json#L18), why is this an issue?

**Comment by cebe** [comment]
Added a note to the readme.

**Comment by schmunk42** [comment]
@cebe btw, if you use `composer require` it would always pick the right constraint, in general I'd remove the manual editing of `composer.json` files. Devs who know what they are doing can still do that, but over time you'd have to add more and more "manual dependency resolution hints" to README(s).

**Comment by cebe** [comment]
`composer require` ususally picks a version constraint that does not fit for Yii, e.g. `^2.0` so adding it manually and showing how it should look like in composer.json is useful.

**Comment by schmunk42** [comment]
True, might be a good thing to add a [compatibility matrix](https://github.com/dmstr/yii2-adminlte-asset#compatibility-matrix) for packages which need it.

Also opened a composer issue about that.
