### ISSUE TITLE
Syntax Errors in files of The SwiftMailer

### ISSUE THREAD

**Issue by shoomlix** [yiisoft/yii2-swiftmailer#60]
### What steps will reproduce the problem?
If ran the console app on hosting by the cron and ran The Swiftmailer by this code
`Yii::$app->mailer->compose()->setFrom(Yii::$app->params['robotEmail'])->setTo('some email')->setSubject('some subject')->send();`
### What's expected?
Only to get true.
### What do you get instead?
Some syntax errors in a lot of swiftmailer files. Like this:

1. PHP Parse Error 'yii\base\ErrorException' with message 'syntax error, unexpected '?''
   in /var/www/vhosts/kupdam.ru/httpdocs/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php:496

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

2. PHP Parse Error 'yii\base\ErrorException' with message 'syntax error, unexpected '?''
    in /var/www/vhosts/kupdam.ru/httpdocs/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php:296

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.15.1
| Yii SwiftMailer version | 2.1.0.0
| SwiftMailer version     | 6.0.2
| PHP version             | 7.1.1
| Operating system        | CentOS Linux 7.2.1511 (Core)‬

**Comment by samdark** [comment]
Would you please post errors here?

**Comment by shoomlix** [comment]
**samdark**, yes of course.

## First.
PHP Parse Error 'yii\base\ErrorException' with message 'syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$''

in /var/www/vhosts/kupdam.ru/httpdocs/common/models/AdsModel.php:244

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

## Second.
PHP Parse Error 'yii\base\ErrorException' with message 'syntax error, unexpected '?''

in /var/www/vhosts/kupdam.ru/httpdocs/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php:496

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

## Third.
PHP Parse Error 'yii\base\ErrorException' with message 'syntax error, unexpected '?''

in /var/www/vhosts/kupdam.ru/httpdocs/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php:296

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

**Comment by rob006** [comment]
Are your sure that you have PHP 7.1.1 on that server? It looks like your PHP does not support null coalescing operator (which is supported from PHP 7.0).

**Comment by shoomlix** [comment]
**rob006**, I can answer to you only by a screenshot.
![php 7](https://user-images.githubusercontent.com/19309630/38245587-d81f48ea-3768-11e8-8c53-f139a71ea20c.png)

**Comment by rob006** [comment]
Can you also answer with result of `die(phpversion())` called before `Yii::$app->mailer->compose()`?

**Comment by shoomlix** [comment]
**rob006**, you're right! God dammit!

I got 5.4.45

But in the panel I see version 7.1.1

How to change it? Could you please give me an advice?

Where

**Comment by rob006** [comment]
You should contact with your hosting provider. 7.1.1 is probably version used by webserver, for cron you may need something like `php71 yii my-command`, but this will depend on server configuration.

**Comment by shoomlix** [comment]
**rob006**, thank you very much.
