### ISSUE TITLE
Not send mail with cyrillic domain

### ISSUE THREAD

**Issue by rsgrey** [yiisoft/yii2-swiftmailer#66]
Not send mail with cyrillic domain
'test@тест.kz Address in mailbox given [test@тест.kz] does not comply with RFC 2822, 3.6.2.'

This bug fixed in swiftmailer https://github.com/swiftmailer/swiftmailer/pull/1044
Plz, update composer.json

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.15.1
| Yii SwiftMailer version | 2.0.7
| SwiftMailer version     | 5.4.9
| PHP version             | 7.2.5
| Operating system        | Ubuntu 16.04.4 LTS

**Comment by rob006** [comment]
You should use 2.1 line, which is compatible with Swiftmailer 6.

https://github.com/yiisoft/yii2-swiftmailer/blob/4faba373f97281c5a3d401b4694733ae32edcd49/composer.json#L22
