### ISSUE TITLE
Cannot work well with Office365's Starttls

### ISSUE THREAD

**Issue by AlineWork** [yiisoft/yii2-swiftmailer#71]
### What steps will reproduce the problem?
Send email with other mailbox succeeded already. Recently my user want to switch the mail server to office 365, so changed the mailbox and did some test, failed to send mail. 

The config file was set as below:
```
    'mailer'=>[
            'class'=>'yii\swiftmailer\Mailer',
            'viewPath'=>'@common/mail',
            'useFileTransport'=>false,
            'transport'=>[
                'class'=>'Swift_SmtpTransport',
                'host'=>'smtp.office365.com',
                'username'=>'myusername@domain.com',
                'password'=>'mypassword',
                'port'=>'587',
                'encryption'=>'START/TLS',
            ],
        ],
```
### What's expected?
mail send success
### What do you get instead?
Connection could not be established with host smtp.office365.com [php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known #0]

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.11
| Yii SwiftMailer version | 2.0.7
| SwiftMailer version     |5.4.8
| PHP version             |5.6.11
| Operating system        |Mac OS

**Comment by cebe** [comment]
>  'encryption'=>'START/TLS',

according to swiftmailer docs, that should be 'tls', not 'START/TLS'.

https://swiftmailer.symfony.com/docs/sending.html#the-smtp-transport

**Comment by AlineWork** [comment]
I tried tls, but get the following error:
Exception
```
Swift_TransportException

Failed to authenticate on SMTP server with username "emailaddress@domain.com" using 2 possible authenticators
```
But I am 100% sure that the email address works good and I can send mail via this address by other mail client. However with my code, it don't work.
