### ISSUE TITLE
return $priority ?? 3; php 7.2

### ISSUE THREAD

**Issue by sergmoro1** [yiisoft/yii2-swiftmailer#72]
The problem with sending mail occurred after updating the PHP version.
Before that, everything was perfect.

PHP Parse Error 'yii\base\ErrorException' with message 'syntax error, unexpected '?''

in /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php:490

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

Here is the problem.
return $priority ?? 3;

My PHP version is

php -v
PHP 7.2.12-1+ubuntu14.04.1+deb.sury.org+1 (cli) (built: Nov 12 2018 10:58:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
with Zend OPcache v7.2.12-1+ubuntu14.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by rob006** [comment]
Are you sure you're using PHP7 to run this code? `return $priority ?? 3` should work perfectly fine on PHP >=7.0

**Comment by sergmoro1** [comment]
1. When ... http://vorst.ru/site/feedback (I keep it in debug mode)
2. In a debug mode:
PHP Parse Error – yii\base\ErrorException
syntax error, unexpected '?'
in /home/sm1/www/vorst/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php at line 490
490 return $priority ?? 3;
3.
4.
5. this piece of code is ordinary and worked great before the version was updated. moreover, when working from the console messages are sent and reach the recipient.

"Are you sure you're using PHP7 to run this code? return $priority ?? 3 should work perfectly fine on PHP >=7.0"

I'm checking the version as usual. Maybe I didn't count on something. What else is worth checking out?

php -v
PHP 7.2.12-1+ubuntu14.04.1+deb.sury.org+1 (cli) (built: Nov 12 2018 10:58:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
with Zend OPcache v7.2.12-1+ubuntu14.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by rob006** [comment]
Try `echo PHP_VERSION_ID` somewhere in this form. You're probably using different PHP for web requests than for console.

**Comment by sergmoro1** [comment]
50509

**Comment by sergmoro1** [comment]
You're probably right. Something's wrong with the versions.
