### ISSUE TITLE
[feature request] Implement CSS inliner

### ISSUE THREAD

**Issue by machour** [yiisoft/yii2-swiftmailer#73]
When sending HTML emails, styles should be inlined for better compatibility with all emails clients.

This is painful when developing views, as I much rather have my CSS in an external file, maintained by LESS or Sass, and simply use classes names in my views.

It would be nice to propose the CSS inlining feature in Yii, by relying on [tijsverkoyen/css-to-inline-styles](https://github.com/tijsverkoyen/CssToInlineStyles) for example.

This package could be a suggested installation, and if it's installed and configured, `Mailer::compose()` would use it on `$html` to inline styles out of the box.

**Comment by rob006** [comment]
I'm already using `openbuildings/swiftmailer-css-inliner` as a plugin without any trouble - why do you need support for it in extension itself?

**Comment by machour** [comment]
Maybe because I was unaware of this plugin :)

How do you configure it? Documentation really needs to be enhanced.

**Comment by rob006** [comment]
```php
		'mailer' => [
			'class' => SwiftMailer::class,
			'messageClass' => Message::class,
			'viewPath' => '@mail/views',
			'transport' => [
				'plugins' => [
					[
						'class' => CssInlinerPlugin::class,
					],
				],
			],
		],
```
