### ISSUE TITLE
Not send mail

### ISSUE THREAD

**Issue by buiduongthe** [yiisoft/yii2-swiftmailer#74]
Dear All,
My Config 
```
'mailer'      => [
            'class'     => 'yii\swiftmailer\Mailer',
            'enableSwiftMailerLogging'	=>	true,
            'viewPath'  => '@common/mail',
            'transport' => [
                'class'      		=> 'Swift_SmtpTransport',
                'host'       		=> 'smtp.domain.com',
                'username'   		=> 'no-reply@doamin.com',
                'password'   		=> 'Password',
                'port'       		=> '465',
                'encryption' 		=> 'ssl',
            ],
        ],
```
And Send mail
$result = Yii::$app->mailer->compose()
            ->setFrom('no-reply@domain.com')
            ->setTo('abc@gmail.com')
            ->setSubject('Message subject Local')
            ->setTextBody('Plain text content')
            ->setHtmlBody('<b>HTML content</b>')
            ->send();

### What steps will reproduce the problem?
I send email from local OK
I send email from Server var_dump -> true. But email not to the recipient
### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | This is Yii version 2.0.16-dev
| Yii SwiftMailer version |  "yiisoft/yii2-swiftmailer": "^2.1@dev",
| SwiftMailer version     | 6.1-dev
| PHP version             | 7.3
| Operating system        | Centos 7 Plesk

Thanks

**Comment by machour** [comment]
What do you see in logs?

**Comment by buiduongthe** [comment]
Dear Mehdi Achour

I can not reply comment of you.

Yii2 not write log send email
My Config log

'log' => [
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],

I change fail password to create an error. But Sys not write log



*Thanks & Best regards*

Name: Bùi Dương Thế
Email: buiduongthe@gmail.com
Skype: buiduongthe
Phone: 0976570931

**Comment by samdark** [comment]
Sorry but we cannot fix the issue if we don't have enough info to reproduce it.

**Comment by buiduongthe** [comment]
Dear All,

I fixed

common/config.php
'mailer'      => [
            'class'     => 'yii\swiftmailer\Mailer',
            'enableSwiftMailerLogging'=>true,
            'viewPath'  => '@common/mail',
            'transport' => [...],
]

and

common/config-local.php

'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'viewPath' => '@common/mail',
            'useFileTransport' => true,
        ],

=> error

Solution

clear mailer in config-local.php

*Thanks & Best regards*

Name: Bùi Dương Thế
Email: buiduongthe@gmail.com
Skype: buiduongthe
Phone: 0976570931
