### ISSUE TITLE
compose() with smarty render 

### ISSUE THREAD

**Issue by andrtechno** [yiisoft/yii2-swiftmailer#78]
config.php
```
        'view' => [
            ..
            'renderers' => [
                'tpl' => [
                    'class' => 'yii\smarty\ViewRenderer',
                ],
            ],
        ],
```

не работает smarty при таком раскладе
`->compose('mail.tpl', [])`
не знаю, не доработка это или так и задумано?!

А вот так работает
`->compose()->setHtmlBody($this->renderPartial('mail.tpl', []))`

**Comment by andrtechno** [comment]
@samdark 

Решение данной проблемы кроется в yii2-framework

https://github.com/yiisoft/yii2-framework/blob/master/mail/BaseMailer.php

функция createView()

```
    protected function createView(array $config)
    {
        if (!array_key_exists('class', $config)) {
            $config['class'] = View::className();
        }
        return Yii::createObject($config);
    }
```

Из-за того что view создается отдельно от конфига приложение, Он попросту не видит view из конфига. Я решил это так. Думаю стоит включить в ядро... Ну или сделать чтобы можно было в конфиге настроивать view для mailer

```
    protected function createView(array $config)
    {
        if (!array_key_exists('class', $config)) {
            $config['class'] = View::className();
            if (Yii::$app->getView()->renderers)
                $config['renderers'] = Yii::$app->getView()->renderers;

        }
        return Yii::createObject($config);
    }
```

**Comment by andrtechno** [comment]
Сори не доглядел что можно в конфиге для mailer прописать renders, можно закрывать тикет.
        'mailer' => [
           ..
            'view'=>[
                'renderers' => [
                    'tpl' => [
                        'class' => 'yii\smarty\ViewRenderer',
                        //'cachePath' => '@runtime/Smarty/cache',
                    ],
                ],
            ]
        ],

**Comment by machour** [comment]
Should be documented here: https://github.com/yiisoft/yii2-smarty/blob/master/docs/guide/installation.md

**Comment by samdark** [comment]
It's already there.
