### ISSUE TITLE
Add method for reset (restart) transport

### ISSUE THREAD

**Issue by unclead** [yiisoft/yii2-swiftmailer#8]
I'm using a worker for sending emails which work as a daemon and i noticed that daemon fails with an error when there is a long period between sending emails

```
Error: fwrite(): send of 6 bytes failed with errno=32 Broken pipe
PHP Notice:  fwrite(): send of 12 bytes failed with errno=32 Broken pipe in .../vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 232
```

I found the swiftmailer's issue about this problem: https://github.com/swiftmailer/swiftmailer/issues/490

One guy implemented his own extension for laravel that has functional for auto reseting smtp connection.
You can find it here: https://github.com/YOzaz/Laravel-SwiftMailer/blob/master/src/YOzaz/LaravelSwiftmailer/Mailer.php#L128

I think we can implement same functionality for avoid such error

**Comment by YOzaz** [comment]
Well, this package is almost framework-independent - shouldn't be hard to upgrade for multiple framework support ;)

**Comment by klimov-paul** [comment]
Rejected: this issue should be solved at `swiftmailer` project level.

**Comment by YOzaz** [comment]
@klimov-paul, my 2 cents: as we have discussed with SwiftMailer author, it should not automatically solve it, as auto-reset is out of project scope and is rather SMTP connection limitation (?). SwiftMailer is only a set of tools, not a framework.
Laravel has already implemented auto-reset functionality in it's latest branch after a long discussion about this.

**Comment by klimov-paul** [comment]
> it should not automatically solve it, as auto-reset is out of project scope and is rather SMTP connection limitation (?). SwiftMailer is only a set of tools, not a framework.

Well, I can say just the same about this extension. Auto-reset of the SMTP connection is risky, since the reson of its failure is unknown.

The obvious solution for this problem will be extending `Swift_SmtpTransport` and overridde its `send()` method with something like following:

```php
public function send(Swift_Mime_Message $message, &$failedRecipients = null)
{
    try {
        parent::send($message, $failedRecipients);
    } catch(\Exception $e) {
        $this->restart();
        $this->send($message, $failedRecipients);
    }
}
```

**Comment by klimov-paul** [comment]
This extension simply do not have a proper place for such wrap.

**Comment by desmondlee** [comment]
@klimov-paul Hi, Thanks for your help! Would you please tell me how exactly to fix this unusual problem in yii2-framework ?

**Comment by cebe** [comment]
@desmondlee the solution is in the comment above. For further help, see below:

**Comment by desmondlee** [comment]
@cebe Thanks a lot!

**Comment by YOzaz** [comment]
https://github.com/YOzaz/Laravel-SwiftMailer/blob/master/src/YOzaz/LaravelSwiftmailer/Mailer.php#L521
