### ISSUE TITLE
Swiftmailer soon won't be maintained anymore

### ISSUE THREAD

**Issue by Deele** [yiisoft/yii2-swiftmailer#88]
Just saw the message in swiftmailer documentation website:

> As of November 2021, Swiftmailer will **not be maintained anymore**. [Use Symfony Mailer](https://symfony.com/doc/current/mailer.html) instead. Read more on [Symfony's blog](https://symfony.com/blog/the-end-of-swiftmailer).

This means that in future, will need to transition to another mailer, like mentioned Symfony mailer.

**Comment by Krakozaber** [comment]
Будет ли свежий адаптер для 2-й версии ?

**Comment by samdark** [comment]
@Krakozaber if you have time to port https://github.com/yiisoft/mailer-symfony, I can create a repository for it.

**Comment by samdark** [comment]
No. Do you want to port it?

**Comment by metola** [comment]
Yes, I can try it.
can you create repository?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-symfonymailer

**Comment by Krakozaber** [comment]
https://github.com/yiisoft/yii2-symfonymailer/issues/1

**Comment by Krakozaber** [comment]
@Deele close this issue ?
