### ISSUE TITLE
Fatal PHP error when configuring a transport class with a protected property

### ISSUE THREAD

**Issue by brandonkelly** [yiisoft/yii2-swiftmailer#9]
If you try to configure yii\swiftmailer\Mailer with a Transport class that has getter/setter methods that correspond to a protected property, if you try to include that property in your Mailer config, it will result in a fatal PHP error because the `property_exists()` method on [line 231 of Mailer.php](https://github.com/yiisoft/yii2-swiftmailer/blob/master/Mailer.php#L231) will return true.

Here’s a concrete example: I’m trying to connect my Yii application to Mandrill using the MandrillTransport class from the [accord/mandrill-swiftmailer](https://github.com/AccordGroup/MandrillSwiftMailer/blob/master/SwiftMailer/MandrillTransport.php) library. MandrillTransport has a [protected $apiKey property](https://github.com/AccordGroup/MandrillSwiftMailer/blob/master/SwiftMailer/MandrillTransport.php#L24) and a [public setApiKey() method](https://github.com/AccordGroup/MandrillSwiftMailer/blob/master/SwiftMailer/MandrillTransport.php#L64). So my mailer config is:

```php
'mailer' => [
    'class' => 'yii\swiftmailer\Mailer',
    'transport' => [
        'class' => 'Accord\MandrillSwiftMailer\SwiftMailer\MandrillTransport',
        'constructArgs' => [
            [
                'class' => 'Swift_Events_SimpleEventDispatcher'
            ]
        ],
        'apiKey' => 'XXXXXXXX',
    ]
]
```

I was expecting that yii\swiftmailer\Mailer would be smart enough to match the `apiKey` setting with the `setApiKey()` method, as that’s what the logic suggests it will do, but instead I got that fatal PHP error due to the protected `$apiKey` property.

**Comment by klimov-paul** [comment]
Issue resolved by commit fffcd50
