### ISSUE TITLE
Update dependency from swiftmailer/swiftmailer to symfony / mailer

### ISSUE THREAD

**Issue by depesr** [yiisoft/yii2-swiftmailer#94]
As said at https://github.com/swiftmailer/swiftmailer Swiftmailer will stop being maintained at the end of November 2021.

Please update composer.json accordingly.

**Comment by rob006** [comment]
You should migrate to https://github.com/yiisoft/yii2-symfonymailer

**Comment by depesr** [comment]
thanks
