### ISSUE TITLE
Moving to Symfony Mailer 

### ISSUE THREAD

**Issue by abilogos** [yiisoft/yii2-swiftmailer#95]
### What's expected?
it has been mentioned in the [swiftmailer](https://github.com/swiftmailer/swiftmailer) that it wont be supported and suggested to move to the symphony mailer, which has a similar api.
I have found out in the composer dependencies which yii2-swiftmailer uses the swiftmailer, and we can change it to symphonyMailer.
in case of any help I would be glad to contribute.

**Comment by bizley** [comment]
https://github.com/yiisoft/yii2-symfonymailer/ ;)
