### ISSUE TITLE
 Swiftmailer extension (yiisoft/yii2-swiftmailer)

### ISSUE THREAD

**Issue by MNaresh072** [yiisoft/yii2-swiftmailer#97]
###   Request for reset password then i found these bug feature , in that domain i already registered then i forgot my password , and then i try to RESET the password.  Then found these at **https://www.bharatacharyaeducation/index.php/site/request-password-reset** when i click on the reset button it redirect to some bunch of yiisoft and yii2 codes with number of errors and some credientials ,POST and cookies  

  _________________
![Screenshot_2022-11-15_21_32_06](https://user-images.githubusercontent.com/103954005/202069361-7f61a4bd-5c31-491d-a176-086d74de3c05.png)
__________________________________________
Swift_TransportException: Expected response code 250 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials a3-20020a621a03000000b0056abff42a8bsm9524605pfa.69 - gsmtp
" in /var/www/html/bae-com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:383
Stack trace:
#0 /var/www/html/bae-com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(281): Swift_Transport_AbstractSmtpTransport->_assertResponseCode('535-5.7.8 Usern...', Array)
#1 /var/www/html/bae-com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(270): Swift_Transport_AbstractSmtpTransport->executeCommand('RSET\r\n', Array, Array)
#2 /var/www/html/bae-com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/Auth/XOAuth2Authenticator.php(55): Swift_Transport_EsmtpTransport->executeCommand('RSET\r\n', Array)
#3 /var/www/html/bae-com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php(176): Swift_Transport_Esmtp_Auth_XOAuth2Authenticator->authenticate(Object(Swift_SmtpTransport), 'test321demo@gma...', 'redhat123@')
#4 /var/www/html/bae-com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(332): Swift_Transport_Esmtp_AuthHandler->afterEhlo(Object(Swift_SmtpTransport))
#5 /var/www/html/bae-com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(118): Swift_Transport_EsmtpTransport->_doHeloCommand()
#6 /var/www/html/bae-com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#7 /var/www/html/bae-com/vendor/yiisoft/yii2-swiftmailer/Mailer.php(146): Swift_Mailer->send(Object(Swift_Message))
#8 /var/www/html/bae-com/vendor/yiisoft/yii2/mail/BaseMailer.php(263): yii\swiftmailer\Mailer->sendMessage(Object(yii\swiftmailer\Message))
#9 /var/www/html/bae-com/vendor/yiisoft/yii2/mail/BaseMessage.php(49): yii\mail\BaseMailer->send(Object(yii\swiftmailer\Message))
#10 /var/www/html/bae-com/frontend/models/PasswordResetRequestForm.php(66): yii\mail\BaseMessage->send()
#11 /var/www/html/bae-com/frontend/controllers/SiteController.php(595): frontend\models\PasswordResetRequestForm->sendEmail()
#12 [internal function]: frontend\controllers\SiteController->actionRequestPasswordReset()
#13 /var/www/html/bae-com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /var/www/html/bae-com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /var/www/html/bae-com/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('request-passwor...', Array)
#16 /var/www/html/bae-com/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('site/request-pa...', Array)
#17 /var/www/html/bae-com/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#18 /var/www/html/bae-com/frontend/web/index.php(17): yii\base\Application->run()
#19 {main}
___________________________________________________________
  

### bounty?

###bounty?

### Additional info

| Q                       | **A**
| ----------------------- | ---
| [Yii Framework/2.0.23  |
| Yii 2.0 Extension |
| Yii 2.0 Extension    |
| PHP version  2.0           |
| on window    and android   |

**Comment by bizley** [comment]
This is something for the website author to fix. Also they should switch to prod mode because they show error stack.
